// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihzbrjynzunppfcwknmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloemJyanluenVucHBmY3drbm15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODI3ODQsImV4cCI6MjA1OTk1ODc4NH0.k8ZSKUcOw2olUPuR8fwo6fOJA3L5645-yO6lMRspIlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);